# Default values for test-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: test-app
appName: user-management-helm
replica: 3
image: hpeartifacts-docker-harmony-local.jfrog.io/akka-http-quickstart-scala:old-tag